/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fss.everythingapp.app;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        System.out.println("App starting...");
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        stage.setTitle("FSS App");
        stage.show();
    }
}
